version: '3.8'
services:
  app:
    build: 
      context: .
    env_file: 
      - ".env"
    environment: 
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
    depends_on: 
      - pg
    ports:
      - "9999:8080"
      
  pg:
    image: "postgres:alpine"
    container_name: "next-db"
    env_file:
      - ".env"
    ports:
      - "5555:5432"
    volumes:
      - "pg:/var/lib/postgresql/data"
    restart: "always"
volumes:
  pg:
